// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrfreauhawplgphgdjvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZnJlYXVoYXdwbGdwaGdkanZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDMwMjgsImV4cCI6MjA3MjY3OTAyOH0.hF9ra8R2Oj1pMNGqkXDNpDAmd6eRYYiT6uz8tVk8chI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});